In [28]:
import torch
import torchvision
import numpy as np
import sys
from time import time
# sys.path.append("..") # 为了导入上层目录的d2lzh_pytorch
# import d2lzh_pytorch as d2l

In [29]:
sys.path

['/Users/steve/Desktop/2020T2/comp9444/pyTorch',
 '/Users/steve/opt/anaconda3/lib/python37.zip',
 '/Users/steve/opt/anaconda3/lib/python3.7',
 '/Users/steve/opt/anaconda3/lib/python3.7/lib-dynload',
 '',
 '/Users/steve/opt/anaconda3/lib/python3.7/site-packages',
 '/Users/steve/opt/anaconda3/lib/python3.7/site-packages/aeosa',
 '/Users/steve/opt/anaconda3/lib/python3.7/site-packages/IPython/extensions',
 '/Users/steve/.ipython',
 '..']

In [30]:
num_inputs = 784
num_outputs = 10

W = torch.tensor(np.random.normal(0, 0.01, (num_inputs, num_outputs)), dtype=torch.float)
b = torch.zeros(num_outputs, dtype=torch.float)

W.requires_grad_(requires_grad=True)
b.requires_grad_(requires_grad=True) 

In [34]:
print(W.shape)
print(W)
print(b.shape)
print(b)

torch.Size([784, 10])
tensor([[ 0.0098,  0.0091,  0.0103,  ...,  0.0044, -0.0026, -0.0058],
        [-0.0114,  0.0060,  0.0111,  ..., -0.0178,  0.0072,  0.0017],
        [ 0.0216, -0.0024, -0.0154,  ..., -0.0155,  0.0049, -0.0073],
        ...,
        [ 0.0007,  0.0103, -0.0008,  ...,  0.0127, -0.0053,  0.0198],
        [-0.0140,  0.0068, -0.0118,  ..., -0.0103, -0.0060, -0.0084],
        [ 0.0026, -0.0048,  0.0159,  ...,  0.0010, -0.0001, -0.0004]])
torch.Size([10])
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])


In [36]:
W.exp()

tensor([[1.0098, 1.0091, 1.0104,  ..., 1.0044, 0.9974, 0.9942],
        [0.9886, 1.0060, 1.0111,  ..., 0.9824, 1.0072, 1.0017],
        [1.0219, 0.9976, 0.9847,  ..., 0.9846, 1.0049, 0.9927],
        ...,
        [1.0007, 1.0104, 0.9992,  ..., 1.0127, 0.9948, 1.0200],
        [0.9861, 1.0068, 0.9883,  ..., 0.9897, 0.9940, 0.9916],
        [1.0026, 0.9952, 1.0161,  ..., 1.0010, 0.9999, 0.9996]])