In [28]:
import torch
import torchvision
import numpy as np
import sys
from time import time
# sys.path.append("..") # 为了导入上层目录的d2lzh_pytorch
# import d2lzh_pytorch as d2l

In [29]:
sys.path

['/Users/steve/Desktop/2020T2/comp9444/pyTorch',
 '/Users/steve/opt/anaconda3/lib/python37.zip',
 '/Users/steve/opt/anaconda3/lib/python3.7',
 '/Users/steve/opt/anaconda3/lib/python3.7/lib-dynload',
 '',
 '/Users/steve/opt/anaconda3/lib/python3.7/site-packages',
 '/Users/steve/opt/anaconda3/lib/python3.7/site-packages/aeosa',
 '/Users/steve/opt/anaconda3/lib/python3.7/site-packages/IPython/extensions',
 '/Users/steve/.ipython',
 '..']

In [30]:
num_inputs = 784
num_outputs = 10

W = torch.tensor(np.random.normal(0, 0.01, (num_inputs, num_outputs)), dtype=torch.float)
b = torch.zeros(num_outputs, dtype=torch.float)

W.requires_grad_(requires_grad=True)
b.requires_grad_(requires_grad=True) 

In [34]:
print(W.shape)
print(W)
print(b.shape)
print(b)

torch.Size([784, 10])
tensor([[ 0.0098,  0.0091,  0.0103,  ...,  0.0044, -0.0026, -0.0058],
        [-0.0114,  0.0060,  0.0111,  ..., -0.0178,  0.0072,  0.0017],
        [ 0.0216, -0.0024, -0.0154,  ..., -0.0155,  0.0049, -0.0073],
        ...,
        [ 0.0007,  0.0103, -0.0008,  ...,  0.0127, -0.0053,  0.0198],
        [-0.0140,  0.0068, -0.0118,  ..., -0.0103, -0.0060, -0.0084],
        [ 0.0026, -0.0048,  0.0159,  ...,  0.0010, -0.0001, -0.0004]])
torch.Size([10])
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])


In [36]:
W.exp()

tensor([[1.0098, 1.0091, 1.0104,  ..., 1.0044, 0.9974, 0.9942],
        [0.9886, 1.0060, 1.0111,  ..., 0.9824, 1.0072, 1.0017],
        [1.0219, 0.9976, 0.9847,  ..., 0.9846, 1.0049, 0.9927],
        ...,
        [1.0007, 1.0104, 0.9992,  ..., 1.0127, 0.9948, 1.0200],
        [0.9861, 1.0068, 0.9883,  ..., 0.9897, 0.9940, 0.9916],
        [1.0026, 0.9952, 1.0161,  ..., 1.0010, 0.9999, 0.9996]])

In [2]:
data = "11-22"
time = data.split('-')[0]
day = data.split('-')[1]
print(time, day)
data

11 22


'11-22'

In [3]:
dic = {'A':1, 'B':2}
dic

{'A': 1, 'B': 2}

In [7]:
list(dic.keys())

['A', 'B']

In [8]:
for i in dic.keys():
    print(i)

A
B


In [9]:
'A' in dic.keys()

True

In [10]:
'aa' == 'aa'


True

In [11]:
soft = {}
type(soft)

dict

In [38]:
soft = [{'t1': 3}, {'t2': 4}]

domain = {}

In [39]:
for var in soft:
    domain[list(var)[0]]={(11,14)}
print(domain)

{'t1': {(11, 14)}, 't2': {(11, 14)}}


In [28]:
type({'A': {1, 2, 3, 4}, 'B': {1, 2, 3, 4}, 'C': {1, 2, 3, 4},
            'D': {1, 2, 3, 4}, 'E': {1, 2, 3, 4}})

dict

In [47]:
def bc_before(t1, t2):
    # 't1': {(start, end), (start, end)...},
    # 't2': {(start, end), (start, end)...}
    return t1[1] <= t2[0]  # t1.end_time <= t2.start_time

In [65]:
# print(soft[0])
day2num = {'mon': 1, 'tue': 2, 'wed': 3, 'thu': 4, 'fri': 5}
for val in day2num.values():
    print(val)


1
2
3
4
5


In [46]:
for i in range(1, 6):
    for j in range(1, 10 - 3):
        print((i * 10 + j, i * 10 + j + 3))

(11, 14)
(12, 15)
(13, 16)
(14, 17)
(15, 18)
(16, 19)
(21, 24)
(22, 25)
(23, 26)
(24, 27)
(25, 28)
(26, 29)
(31, 34)
(32, 35)
(33, 36)
(34, 37)
(35, 38)
(36, 39)
(41, 44)
(42, 45)
(43, 46)
(44, 47)
(45, 48)
(46, 49)
(51, 54)
(52, 55)
(53, 56)
(54, 57)
(55, 58)
(56, 59)


In [62]:
print(set(sorted({(i * 10 + j, i * 10 + j + 3) for i in range(1, 6) for j in range(1, 10 - 3)})))

{(14, 17), (21, 24), (33, 36), (11, 14), (23, 26), (43, 46), (51, 54), (55, 58), (24, 27), (26, 29), (13, 16), (45, 48), (15, 18), (36, 39), (46, 49), (42, 45), (31, 34), (53, 56), (32, 35), (34, 37), (16, 19), (25, 28), (12, 15), (22, 25), (44, 47), (52, 55), (54, 57), (56, 59), (35, 38), (41, 44)}
